### ISSUE TITLE
Duplicated genes in v.14.1

### ISSUE THREAD

**Issue by huaiyumi** [pantherdb/library_building#10]
This is from a user feedback. The following two long IDs are both in our database.
HUMAN|HGNC=4067|UniProtKB=H6UMI1
HUMAN|HGNC=4067|UniProtKB=O95166

The same gene ID (HGNC=4067) is mapped to two uniprot IDs. Only one should be included. The middle part (gene identifiers) should be unique. Let's make sure it is fixed in v.15.0

**Comment by dustine32** [comment]
`HUMAN|HGNC=4067|UniProtKB=O95166` is currently the only `HGNC=4067` entry we have in our 15.0 mapping file so we should be good. I did some work a month or two ago to ensure that this middle ID is distinct within the same organism, using sequence length or even alphabetic sorting to determine which to keep. 3315 sequences were dropped by this.

I didn't see any `HGNC=4067` is this dropped sequences list so this issue must have been handled upstream by either UniProt or HGNC.

**Comment by huaiyumi** [comment]
Good. I will close it then.
