### ISSUE TITLE
protein_node table data missing

### ISSUE THREAD

**Issue by huaiyumi** [pantherdb/library_building#4]
It looks like the 14.1 data is missing in the protein_node table in the curation database (panthertestdb.usc.edu). This resulted in the failure of loading the gene description in the paint tool. The paint tool uses the following query:

select n.accession, it.IDENTIFIER_TYPE_SID, i.NAME, it.name as identifier_type 
from node n, protein_node pn, protein p, identifier i, identifier_type it
where n.classification_version_sid = 26 
and n.accession like 'PTHR10000%' 
and n.node_id = pn.node_id 
and pn.protein_id = p.protein_id 
and p.PROTEIN_ID = i.primary_object_id 
and i.IDENTIFIER_TYPE_SID = it.IDENTIFIER_TYPE_SID 
and it.IDENTIFIER_TYPE_SID in (3,12) 
and n.OBSOLESCENCE_DATE is null 
and p.OBSOLESCENCE_DATE is null 
and i.OBSOLESCENCE_DATE is null;

The query works in both test database and production database.

**Comment by dustine32** [comment]
@mugitty Do you know if this query is looking at the `panther` or `panther_upl` schema Curation DB?

**Comment by mugitty** [comment]
This happens on PantherTestDB with schema Curation and user panther_upl

**Comment by dustine32** [comment]
Data appears to be loaded into `panther.protein_node` on both calv-panthergres and pantherdb servers but not panthertestdb. It looks like I just need to copy the `panther.protein_node` table data to panthertestdb.Curation DB.

**Comment by dustine32** [comment]
@mugitty This should be fixed now. I'm now getting results for the above PTHR10000 query.

To fix, I had to fill in 14.1 data for `panther.protein_node`, `panther.protein`, and `panther.identifier` on `panthertestdb.Curation`.

**Comment by mugitty** [comment]
@dustine32 @huaiyumi , I opened a sample book using PAINT and the definitions are showing up on the protein information panel

**Comment by mugitty** [comment]
@dustine32 , I saw the definitions a few hours ago. They are no longer showing up.

**Comment by dustine32** [comment]
@mugitty Hmm, do you remember the test book that worked earlier today?

I haven't updated anything else on panthertestdb since.

**Comment by dustine32** [comment]
@mugitty I'm still getting results for the above PTHR10000 query (server: panthertestdb, DB: Curation, schema: panther):
```
select n.accession, it.IDENTIFIER_TYPE_SID, i.NAME, it.name as identifier_type
from node n, protein_node pn, protein p, identifier i, identifier_type it
where n.classification_version_sid = 26
and n.accession like 'PTHR10000%'
and n.node_id = pn.node_id
and pn.protein_id = p.protein_id
and p.PROTEIN_ID = i.primary_object_id
and i.IDENTIFIER_TYPE_SID = it.IDENTIFIER_TYPE_SID
and it.IDENTIFIER_TYPE_SID in (3,12)
and n.OBSOLESCENCE_DATE is null
and p.OBSOLESCENCE_DATE is null
and i.OBSOLESCENCE_DATE is null;
```
For instance, `PTHR10000:AN17` has definition "Haloacid dehalogenase-like hydrolase, putative". From debugging the PAINT tool code, are you able to see what happens to these results immediately after querying the DB?

**Comment by mugitty** [comment]
@dustine32 , you have to use schema panther_upl

**Comment by dustine32** [comment]
@mugitty Oh, in that case I'm puzzled why it works with the test database (calv-panthergres) since schema panther_upl returns no results but schema panther does.

Regardless, I do see that results are returned for 13.1 (`n.classification_version_sid = 24`) when running above query against schema panther_upl on panthertestdb, so I'll look into why 14.1 wasn't loaded into schema panther_upl.

**Comment by dustine32** [comment]
@mugitty Just loaded `protein_node` on schema `panther_upl`, DB server `panthertestdb`, and I'm now getting results when running our PTHR10000 test query against schema `panther_upl`. Do the descriptions appear in the PAINT tool now?

**Comment by mugitty** [comment]
@dustine32 , I can see them now!
